// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTI0ODwYIZ2kPRCNl-jqdKdGne0NzUTQw',
    appId: '1:818789905198:web:9112be4cf48b9cad3480bf',
    messagingSenderId: '818789905198',
    projectId: 'electro-maps-7bc45',
    authDomain: 'electro-maps-7bc45.firebaseapp.com',
    storageBucket: 'electro-maps-7bc45.appspot.com',
    measurementId: 'G-QBZZ3GW25T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB4wMsArKmmNOVPlQQsiT0aJDjn1yAE4k',
    appId: '1:818789905198:android:6d97833a8d3c81043480bf',
    messagingSenderId: '818789905198',
    projectId: 'electro-maps-7bc45',
    storageBucket: 'electro-maps-7bc45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZMQbb8fveM8cl5pBeqNZUqoJaVmFTwbg',
    appId: '1:818789905198:ios:c61eba441bd04f423480bf',
    messagingSenderId: '818789905198',
    projectId: 'electro-maps-7bc45',
    storageBucket: 'electro-maps-7bc45.appspot.com',
    iosBundleId: 'com.mugeep.eElectromaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZMQbb8fveM8cl5pBeqNZUqoJaVmFTwbg',
    appId: '1:818789905198:ios:1dacf313051d38013480bf',
    messagingSenderId: '818789905198',
    projectId: 'electro-maps-7bc45',
    storageBucket: 'electro-maps-7bc45.appspot.com',
    iosBundleId: 'com.mugeep.eElectromaps.RunnerTests',
  );
}
